apps:
  - script: "/bin/bash"
    args:
      ["-c", "run gunicorn --bind 0.0.0.0:9090 --pythonpath 'app' server:app"]
    name: "mkha"
    instances: 1
    watch: false
    log_date_format: "YYYY-MM-DD HH:mm Z"
    combine_logs: true
